### ISSUE TITLE
Gmail threads unrelated Wiredash emails together

### ISSUE THREAD

**Issue by percula** [wiredashio/wiredash-sdk#192]
This isn't really a bug in the SDK, but a bug in the backend. I mentioned this to you guys last year over a video chat and it's still my number 1 gripe with the service. The email integration sends emails with the same subject, which causes Gmail to create threads on unrelated Wiredash emails. For instance, I got 3 separate bug reports and Gmail wrapped them into one conversation. I don't want to disable Gmails threading feature because it's very useful. I believe this issue would be easily fixed by appending a unique string, such as the user ID, to the email subject. Please and thank you 🙏.

**Comment by percula** [comment]
Hi. Still happening, here's what I found in my inbox this morning:

![gmail threading](https://user-images.githubusercontent.com/16809252/161559180-47117f48-c08a-45cf-80de-f712ab1c403c.png)

**Comment by percula** [comment]
Hello?! Anyone there? I'm a paying customer but the lack of any responses to github issues has me thinking of switching to another bug report tool or making my own tool.

**Comment by flschweiger** [comment]
Hey @percula, we've been working on a completely new infrastructure and SDK (as you can see with the current alpha versions) of Wiredash. That's why we're currently not adding any new features to the old system but we will be done sooonish and then we'll also have a bigger amount of integrations to choose from. Also the email notifications will get updated, so stay tuned 🙂

Feel free to shoot us an email to hey@wiredash.io so we can upgrade your plan for free until we've fixed your problem. Sounds fair? Warm greetings from Germany!

**Comment by percula** [comment]
Hey @flschweiger and @passsy, just wanted to give this issue a quick bump! It's still happening with the new infrastructure. Please please please have a look at this. It should be as simple as adding a unique string like the User ID (if non-null) to the email's subject line. Thanks!

**Comment by flschweiger** [comment]
Hey @percula, we just deployed a fix for this problem by including a short preview in the subject. Let us know if that worked for you 🙂

**Comment by percula** [comment]
It works!! Thank you!
